// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeviceWithMerchantAndTenant = `-- name: GetDeviceWithMerchantAndTenant :one
SELECT
    d.device_id,
    d.merchant_id,
    d.tenant_id,
    d.mqtt_topic,
    d.manjo_store_id,
    d.manjo_terminal_id,
    d.status AS device_status,
    m.manjo_client_id,
    m.manjo_private_key_ref,
    m.manjo_client_secret_ref,
    m.manjo_merchant_id,
    m.manjo_channel_id,
    m.status AS merchant_active_status,
    t.manjo_sub_merchant_id,
    t.status AS tenant_active_status
FROM devices d
JOIN merchants m ON m.merchant_id = d.merchant_id
LEFT JOIN tenants t ON t.tenant_id = d.tenant_id
WHERE d.device_id = $1
`

type GetDeviceWithMerchantAndTenantRow struct {
	DeviceID             string             `json:"device_id"`
	MerchantID           string             `json:"merchant_id"`
	TenantID             pgtype.Text        `json:"tenant_id"`
	MqttTopic            string             `json:"mqtt_topic"`
	ManjoStoreID         pgtype.Text        `json:"manjo_store_id"`
	ManjoTerminalID      pgtype.Text        `json:"manjo_terminal_id"`
	DeviceStatus         MerchantStatus     `json:"device_status"`
	ManjoClientID        string             `json:"manjo_client_id"`
	ManjoPrivateKeyRef   string             `json:"manjo_private_key_ref"`
	ManjoClientSecretRef string             `json:"manjo_client_secret_ref"`
	ManjoMerchantID      string             `json:"manjo_merchant_id"`
	ManjoChannelID       string             `json:"manjo_channel_id"`
	MerchantActiveStatus MerchantStatus     `json:"merchant_active_status"`
	ManjoSubMerchantID   pgtype.Text        `json:"manjo_sub_merchant_id"`
	TenantActiveStatus   NullMerchantStatus `json:"tenant_active_status"`
}

func (q *Queries) GetDeviceWithMerchantAndTenant(ctx context.Context, deviceID string) (GetDeviceWithMerchantAndTenantRow, error) {
	row := q.db.QueryRow(ctx, getDeviceWithMerchantAndTenant, deviceID)
	var i GetDeviceWithMerchantAndTenantRow
	err := row.Scan(
		&i.DeviceID,
		&i.MerchantID,
		&i.TenantID,
		&i.MqttTopic,
		&i.ManjoStoreID,
		&i.ManjoTerminalID,
		&i.DeviceStatus,
		&i.ManjoClientID,
		&i.ManjoPrivateKeyRef,
		&i.ManjoClientSecretRef,
		&i.ManjoMerchantID,
		&i.ManjoChannelID,
		&i.MerchantActiveStatus,
		&i.ManjoSubMerchantID,
		&i.TenantActiveStatus,
	)
	return i, err
}
