// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manjo_api_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const logManjoAPICall = `-- name: LogManjoAPICall :one
INSERT INTO manjo_api_logs (direction, operation, endpoint, http_status, request_body, response_body, transaction_id, duration_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, direction, operation, endpoint, http_status, request_body, response_body, transaction_id, duration_ms, created_at
`

type LogManjoAPICallParams struct {
	Direction     ManjoApiDirection `json:"direction"`
	Operation     ManjoApiOperation `json:"operation"`
	Endpoint      string            `json:"endpoint"`
	HttpStatus    pgtype.Int4       `json:"http_status"`
	RequestBody   []byte            `json:"request_body"`
	ResponseBody  []byte            `json:"response_body"`
	TransactionID pgtype.Text       `json:"transaction_id"`
	DurationMs    pgtype.Int4       `json:"duration_ms"`
}

func (q *Queries) LogManjoAPICall(ctx context.Context, arg LogManjoAPICallParams) (ManjoApiLog, error) {
	row := q.db.QueryRow(ctx, logManjoAPICall,
		arg.Direction,
		arg.Operation,
		arg.Endpoint,
		arg.HttpStatus,
		arg.RequestBody,
		arg.ResponseBody,
		arg.TransactionID,
		arg.DurationMs,
	)
	var i ManjoApiLog
	err := row.Scan(
		&i.ID,
		&i.Direction,
		&i.Operation,
		&i.Endpoint,
		&i.HttpStatus,
		&i.RequestBody,
		&i.ResponseBody,
		&i.TransactionID,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}
