// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ManjoApiDirection string

const (
	ManjoApiDirectionOUTBOUND ManjoApiDirection = "OUTBOUND"
	ManjoApiDirectionINBOUND  ManjoApiDirection = "INBOUND"
)

func (e *ManjoApiDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ManjoApiDirection(s)
	case string:
		*e = ManjoApiDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for ManjoApiDirection: %T", src)
	}
	return nil
}

type NullManjoApiDirection struct {
	ManjoApiDirection ManjoApiDirection `json:"manjo_api_direction"`
	Valid             bool              `json:"valid"` // Valid is true if ManjoApiDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullManjoApiDirection) Scan(value interface{}) error {
	if value == nil {
		ns.ManjoApiDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ManjoApiDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullManjoApiDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ManjoApiDirection), nil
}

type ManjoApiOperation string

const (
	ManjoApiOperationACCESSTOKEN   ManjoApiOperation = "ACCESS_TOKEN"
	ManjoApiOperationGENERATEQR    ManjoApiOperation = "GENERATE_QR"
	ManjoApiOperationQUERYPAYMENT  ManjoApiOperation = "QUERY_PAYMENT"
	ManjoApiOperationPAYMENTNOTIFY ManjoApiOperation = "PAYMENT_NOTIFY"
)

func (e *ManjoApiOperation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ManjoApiOperation(s)
	case string:
		*e = ManjoApiOperation(s)
	default:
		return fmt.Errorf("unsupported scan type for ManjoApiOperation: %T", src)
	}
	return nil
}

type NullManjoApiOperation struct {
	ManjoApiOperation ManjoApiOperation `json:"manjo_api_operation"`
	Valid             bool              `json:"valid"` // Valid is true if ManjoApiOperation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullManjoApiOperation) Scan(value interface{}) error {
	if value == nil {
		ns.ManjoApiOperation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ManjoApiOperation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullManjoApiOperation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ManjoApiOperation), nil
}

type MerchantStatus string

const (
	MerchantStatusACTIVE   MerchantStatus = "ACTIVE"
	MerchantStatusINACTIVE MerchantStatus = "INACTIVE"
)

func (e *MerchantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MerchantStatus(s)
	case string:
		*e = MerchantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MerchantStatus: %T", src)
	}
	return nil
}

type NullMerchantStatus struct {
	MerchantStatus MerchantStatus `json:"merchant_status"`
	Valid          bool           `json:"valid"` // Valid is true if MerchantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMerchantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MerchantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MerchantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMerchantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MerchantStatus), nil
}

type MqttDirection string

const (
	MqttDirectionINBOUND  MqttDirection = "INBOUND"
	MqttDirectionOUTBOUND MqttDirection = "OUTBOUND"
)

func (e *MqttDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MqttDirection(s)
	case string:
		*e = MqttDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for MqttDirection: %T", src)
	}
	return nil
}

type NullMqttDirection struct {
	MqttDirection MqttDirection `json:"mqtt_direction"`
	Valid         bool          `json:"valid"` // Valid is true if MqttDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMqttDirection) Scan(value interface{}) error {
	if value == nil {
		ns.MqttDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MqttDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMqttDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MqttDirection), nil
}

type MqttMessageStatus string

const (
	MqttMessageStatusRECEIVED  MqttMessageStatus = "RECEIVED"
	MqttMessageStatusPROCESSED MqttMessageStatus = "PROCESSED"
	MqttMessageStatusFAILED    MqttMessageStatus = "FAILED"
)

func (e *MqttMessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MqttMessageStatus(s)
	case string:
		*e = MqttMessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MqttMessageStatus: %T", src)
	}
	return nil
}

type NullMqttMessageStatus struct {
	MqttMessageStatus MqttMessageStatus `json:"mqtt_message_status"`
	Valid             bool              `json:"valid"` // Valid is true if MqttMessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMqttMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MqttMessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MqttMessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMqttMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MqttMessageStatus), nil
}

type TransactionStatus string

const (
	TransactionStatusPENDING     TransactionStatus = "PENDING"
	TransactionStatusQRGENERATED TransactionStatus = "QR_GENERATED"
	TransactionStatusPAID        TransactionStatus = "PAID"
	TransactionStatusFAILED      TransactionStatus = "FAILED"
	TransactionStatusEXPIRED     TransactionStatus = "EXPIRED"
	TransactionStatusCANCELLED   TransactionStatus = "CANCELLED"
	TransactionStatusREFUNDED    TransactionStatus = "REFUNDED"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus `json:"transaction_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type Device struct {
	ID              pgtype.UUID        `json:"id"`
	DeviceID        string             `json:"device_id"`
	MerchantID      string             `json:"merchant_id"`
	TenantID        pgtype.Text        `json:"tenant_id"`
	MqttTopic       string             `json:"mqtt_topic"`
	ManjoStoreID    pgtype.Text        `json:"manjo_store_id"`
	ManjoTerminalID pgtype.Text        `json:"manjo_terminal_id"`
	Status          MerchantStatus     `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ManjoApiLog struct {
	ID            pgtype.UUID        `json:"id"`
	Direction     ManjoApiDirection  `json:"direction"`
	Operation     ManjoApiOperation  `json:"operation"`
	Endpoint      string             `json:"endpoint"`
	HttpStatus    pgtype.Int4        `json:"http_status"`
	RequestBody   []byte             `json:"request_body"`
	ResponseBody  []byte             `json:"response_body"`
	TransactionID pgtype.Text        `json:"transaction_id"`
	DurationMs    pgtype.Int4        `json:"duration_ms"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Merchant struct {
	ID                   pgtype.UUID        `json:"id"`
	MerchantID           string             `json:"merchant_id"`
	ManjoClientID        string             `json:"manjo_client_id"`
	ManjoPrivateKeyRef   string             `json:"manjo_private_key_ref"`
	ManjoClientSecretRef string             `json:"manjo_client_secret_ref"`
	ManjoMerchantID      string             `json:"manjo_merchant_id"`
	ManjoChannelID       string             `json:"manjo_channel_id"`
	Status               MerchantStatus     `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type MqttMessage struct {
	ID            pgtype.UUID        `json:"id"`
	Topic         string             `json:"topic"`
	Payload       []byte             `json:"payload"`
	Direction     MqttDirection      `json:"direction"`
	Status        MqttMessageStatus  `json:"status"`
	TransactionID pgtype.Text        `json:"transaction_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
}

type Tenant struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           string             `json:"tenant_id"`
	MerchantID         string             `json:"merchant_id"`
	ManjoSubMerchantID pgtype.Text        `json:"manjo_sub_merchant_id"`
	Name               pgtype.Text        `json:"name"`
	Status             MerchantStatus     `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID              pgtype.UUID        `json:"id"`
	TransactionID   string             `json:"transaction_id"`
	ReferenceNo     pgtype.Text        `json:"reference_no"`
	MerchantID      string             `json:"merchant_id"`
	Amount          int64              `json:"amount"`
	Status          TransactionStatus  `json:"status"`
	ManjoStatusCode pgtype.Text        `json:"manjo_status_code"`
	QrisPayload     pgtype.Text        `json:"qris_payload"`
	ExternalID      pgtype.Text        `json:"external_id"`
	ExpireAt        pgtype.Timestamptz `json:"expire_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeviceID        string             `json:"device_id"`
}
