// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mqtt_messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const logMQTTMessage = `-- name: LogMQTTMessage :one
INSERT INTO mqtt_messages (topic, payload, direction, status, transaction_id, error_message, processed_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING id, topic, payload, direction, status, transaction_id, created_at, processed_at, error_message
`

type LogMQTTMessageParams struct {
	Topic         string            `json:"topic"`
	Payload       []byte            `json:"payload"`
	Direction     MqttDirection     `json:"direction"`
	Status        MqttMessageStatus `json:"status"`
	TransactionID pgtype.Text       `json:"transaction_id"`
	ErrorMessage  pgtype.Text       `json:"error_message"`
}

func (q *Queries) LogMQTTMessage(ctx context.Context, arg LogMQTTMessageParams) (MqttMessage, error) {
	row := q.db.QueryRow(ctx, logMQTTMessage,
		arg.Topic,
		arg.Payload,
		arg.Direction,
		arg.Status,
		arg.TransactionID,
		arg.ErrorMessage,
	)
	var i MqttMessage
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Payload,
		&i.Direction,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.ErrorMessage,
	)
	return i, err
}
