// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (transaction_id, merchant_id, device_id, amount, status)
VALUES ($1, $2, $3, $4, 'PENDING')
RETURNING id, transaction_id, reference_no, merchant_id, amount, status, manjo_status_code, qris_payload, external_id, expire_at, created_at, paid_at, updated_at, device_id
`

type CreateTransactionParams struct {
	TransactionID string `json:"transaction_id"`
	MerchantID    string `json:"merchant_id"`
	DeviceID      string `json:"device_id"`
	Amount        int64  `json:"amount"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.TransactionID,
		arg.MerchantID,
		arg.DeviceID,
		arg.Amount,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ReferenceNo,
		&i.MerchantID,
		&i.Amount,
		&i.Status,
		&i.ManjoStatusCode,
		&i.QrisPayload,
		&i.ExternalID,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.PaidAt,
		&i.UpdatedAt,
		&i.DeviceID,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, transaction_id, reference_no, merchant_id, amount, status, manjo_status_code, qris_payload, external_id, expire_at, created_at, paid_at, updated_at, device_id FROM transactions WHERE transaction_id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, transactionID string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, transactionID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ReferenceNo,
		&i.MerchantID,
		&i.Amount,
		&i.Status,
		&i.ManjoStatusCode,
		&i.QrisPayload,
		&i.ExternalID,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.PaidAt,
		&i.UpdatedAt,
		&i.DeviceID,
	)
	return i, err
}

const markTransactionFailed = `-- name: MarkTransactionFailed :one
UPDATE transactions
SET status = 'FAILED',
    updated_at = now()
WHERE transaction_id = $1
RETURNING id, transaction_id, reference_no, merchant_id, amount, status, manjo_status_code, qris_payload, external_id, expire_at, created_at, paid_at, updated_at, device_id
`

func (q *Queries) MarkTransactionFailed(ctx context.Context, transactionID string) (Transaction, error) {
	row := q.db.QueryRow(ctx, markTransactionFailed, transactionID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ReferenceNo,
		&i.MerchantID,
		&i.Amount,
		&i.Status,
		&i.ManjoStatusCode,
		&i.QrisPayload,
		&i.ExternalID,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.PaidAt,
		&i.UpdatedAt,
		&i.DeviceID,
	)
	return i, err
}

const markTransactionQRGenerated = `-- name: MarkTransactionQRGenerated :one
UPDATE transactions
SET status = 'QR_GENERATED',
    qris_payload = $2,
    reference_no = $3,
    external_id = $4,
    expire_at = $5,
    updated_at = now()
WHERE transaction_id = $1
RETURNING id, transaction_id, reference_no, merchant_id, amount, status, manjo_status_code, qris_payload, external_id, expire_at, created_at, paid_at, updated_at, device_id
`

type MarkTransactionQRGeneratedParams struct {
	TransactionID string             `json:"transaction_id"`
	QrisPayload   pgtype.Text        `json:"qris_payload"`
	ReferenceNo   pgtype.Text        `json:"reference_no"`
	ExternalID    pgtype.Text        `json:"external_id"`
	ExpireAt      pgtype.Timestamptz `json:"expire_at"`
}

func (q *Queries) MarkTransactionQRGenerated(ctx context.Context, arg MarkTransactionQRGeneratedParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, markTransactionQRGenerated,
		arg.TransactionID,
		arg.QrisPayload,
		arg.ReferenceNo,
		arg.ExternalID,
		arg.ExpireAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ReferenceNo,
		&i.MerchantID,
		&i.Amount,
		&i.Status,
		&i.ManjoStatusCode,
		&i.QrisPayload,
		&i.ExternalID,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.PaidAt,
		&i.UpdatedAt,
		&i.DeviceID,
	)
	return i, err
}
